import { describe, expect, test } from "bun:test";

const repoRoot = new URL("../../../", import.meta.url).pathname;

/**
 * `bun pm pack --dry-run` runs `prepack`, so the Vite build that produces
 * `packages/web/dist/client` is part of what this asserts. Synchronous so the
 * built-client assertions can be skipped at collection time on a checkout
 * where the web toolchain is unavailable.
 */
function packedPaths(): readonly string[] {
  const packed = Bun.spawnSync(["bun", "pm", "pack", "--dry-run"], {
    cwd: repoRoot,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (packed.exitCode !== 0) {
    throw new Error(
      `bun pm pack --dry-run failed:\n${packed.stderr.toString()}`
    );
  }
  return packed.stdout
    .toString()
    .split("\n")
    .flatMap((line) => {
      const match = /^packed\s+\S+\s+(.+)$/.exec(line.trim());
      return match ? [match[1]!] : [];
    });
}

const paths = packedPaths();
const builtClient = paths.filter((path) =>
  path.startsWith("packages/web/dist/client/")
);

describe("the published tarball", () => {
  test("is not empty", () => {
    expect(paths.length).toBeGreaterThan(50);
  });

  test.each([
    "bin/pim.ts",
    "packages/core/src/extensions/bash/index.ts",
    "packages/tui/src/extensions/_init/index.ts",
    "packages/telegram/src/index.ts",
    // pim's themes are loaded from disk at runtime; nothing else guards them.
    "packages/tui/src/themes/pim-dark.json",
    "packages/tui/src/themes/pim-light.json",
  ])("ships %s", (path) => {
    expect(paths).toContain(path);
  });

  test.each(["packages/protocol/src/", "packages/server/src/"])(
    "ships %s",
    (prefix) => {
      expect(
        paths.filter((path) => path.startsWith(prefix)).length
      ).toBeGreaterThan(0);
    }
  );

  test.skipIf(builtClient.length === 0)(
    "ships the built web client, which is generated by prepack and never committed",
    () => {
      expect(builtClient).toContain("packages/web/dist/client/index.html");
      expect(builtClient.some((path) => path.endsWith(".js"))).toBe(true);
      expect(builtClient.some((path) => path.endsWith(".css"))).toBe(true);
    }
  );

  test("does not ship web sources, only the built client", () => {
    expect(
      paths.filter((path) => path.startsWith("packages/web/src/"))
    ).toEqual([]);
  });

  test("does not ship tests or fixtures", () => {
    expect(paths.filter((path) => path.endsWith(".test.ts"))).toEqual([]);
    expect(
      paths.filter((path) =>
        path.includes("packages/core/src/session/fixtures/")
      )
    ).toEqual([]);
  });
});

if (builtClient.length === 0) {
  console.warn(
    "packaging.test.ts: no packages/web/dist/client in the tarball — `prepack` (bun run build:web) did not produce one; skipping the built-client assertions."
  );
}
